### ISSUE TITLE
Lags a little bit when dragging

### ISSUE THREAD

**Issue by mingrui** [maubreville/SlideRunner#2]
Hi!
Thanks for this great software!

I have a question about the lag when dragging a wsi image, it seems to lag more than running the openslide deepzoom server, is this a known performance issue? thanks!

**Comment by maubreville** [comment]
This is true and known indeed. It comes from the internal structure of the software, because it will not pre-fetch anything and query the openslide library for every view it is about to display. This makes it slow especially for large files and traditional hard drives. 

I think this could be mitigated by loading larger grids from the disk and only reload when the grid has been left. 

I would be curious to know: Is this a major impairment for your application? For what purpose are you using it? :-) 

Anyway, thanks for the feedback!

**Comment by mingrui** [comment]
It's much faster, thank you!
