### ISSUE TITLE
minor usability enhancement: loading lags when switching between zoom levels

### ISSUE THREAD

**Issue by mingrui** [maubreville/SlideRunner#9]
This is related to https://github.com/maubreville/SlideRunner/issues/2

Right now dragging speed is perfect, but when switching between zoom levels, there is still a very noticeable lag, this is a little harder to describe, in the video you can see that when zooming within a zoom level, it's pretty smooth, but when I continue to zoom past a certain threshold level, it lags for a few seconds before catching up to my mouse pointer.

When using a mouse scroll wheel, it's much more noticeable.

Here is the video: https://drive.google.com/open?id=1Ep7ZwxrSP7dkaWYmb2ZSGoSUeiA_kW0i

**Comment by mingrui** [comment]
I was thinking maybe a easier work around is to add zoom level buttons to be able to jump straight to the desired zoom level, and when I scroll I can't accidentally go pass that level. 

Because a really big workflow hindrance right now for me is when I'm zoom in/out alot just to move around faster, but then sometimes I zoom past a zoom level and have to wait a few seconds.

**Comment by maubreville** [comment]
I like that idea. Let me figure out how to do this.

**Comment by maubreville** [comment]
Turns out it's rather tricky to know when reloading takes place, because it's not only about scale but also about the part you're seing. When zooming out, in many cases the current frame will still be within the cache (cache is current frame +/- one complete image width and height). However, if you zoom out, it can happen that you run out of the image before you run into a different scale.

**Comment by mingrui** [comment]
Hmmm... I see what you mean.
